// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subastas.Infrastructure.Data;

#nullable disable

namespace Subastas.Infrastructure.Migrations
{
    [DbContext(typeof(SubastaContext))]
    partial class SubastaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Subastas.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdEmpresa")
                        .HasName("PK__Empresa__75D2CED44086D3C7");

                    b.HasIndex(new[] { "Cif" }, "UQ__Empresa__D837D05C040BA45A")
                        .IsUnique();

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.ImagenVehiculo", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<byte>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ruta")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdImagen")
                        .HasName("PK__ImagenVe__EA9A7136BBBF0FF8");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("ImagenVehiculo");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("IdSubasta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<byte>("Leida")
                        .HasColumnType("tinyint");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNotificacion")
                        .HasName("PK__Notifica__AFE1D7E48069B189");

                    b.HasIndex("IdSubasta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("Subastas.Domain.Entities.NotificacionAdmin", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("DatosAdicionales")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<byte>("Leida")
                        .HasColumnType("tinyint");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("NotificacionAdmin", (string)null);
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("FechaPago")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("IdPuja")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdPago")
                        .HasName("PK__Pago__BD2295AD68E6A9EE");

                    b.HasIndex("IdPuja");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Puja", b =>
                {
                    b.Property<int>("IdPuja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuja"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("FechaPuja")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("IdSubasta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdPuja")
                        .HasName("PK__Puja__B4598EC6C86DB51A");

                    b.HasIndex("IdSubasta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Puja");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("IdSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubasta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("activa");

                    b.Property<DateTime>("FechaFin")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("FechaInicio")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PrecioActual")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("PrecioInicial")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdSubasta")
                        .HasName("PK__Subasta__710C9B2556003E5C");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Subasta");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<byte>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dni")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("DocumentoIAE")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FotoPerfilBase64")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("registrado");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("Validado")
                        .HasColumnType("tinyint");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__645723A6CA1F7D0A");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__AB6E616411E2D183")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int?>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("registrado");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaMatriculacion")
                        .HasColumnType("date");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NumeroPuertas")
                        .HasColumnType("int");

                    b.Property<int?>("Potencia")
                        .HasColumnType("int");

                    b.Property<string>("TipoCarroceria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoMotor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdVehiculo")
                        .HasName("PK__Vehiculo__4868297046AD87EF");

                    b.HasIndex(new[] { "Matricula" }, "UQ__Vehiculo__30962D1527B6AAEF")
                        .IsUnique();

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.ImagenVehiculo", b =>
                {
                    b.HasOne("Subastas.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("ImagenesVehiculo")
                        .HasForeignKey("IdVehiculo")
                        .IsRequired()
                        .HasConstraintName("FK_ImagenVehiculo_Vehiculo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Subastas.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdSubasta")
                        .IsRequired()
                        .HasConstraintName("FK_Notificacion_Subasta");

                    b.HasOne("Subastas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Notificacion_Usuario");

                    b.Navigation("Subasta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.NotificacionAdmin", b =>
                {
                    b.HasOne("Subastas.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Subastas.Domain.Entities.Puja", "Puja")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPuja")
                        .IsRequired()
                        .HasConstraintName("FK_Pago_Puja");

                    b.Navigation("Puja");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Puja", b =>
                {
                    b.HasOne("Subastas.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("IdSubasta")
                        .IsRequired()
                        .HasConstraintName("FK_Puja_Subasta");

                    b.HasOne("Subastas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pujas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Puja_Usuario");

                    b.Navigation("Subasta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Subasta", b =>
                {
                    b.HasOne("Subastas.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Subastas")
                        .HasForeignKey("IdVehiculo")
                        .IsRequired()
                        .HasConstraintName("FK_Subasta_Vehiculo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Subastas.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Usuario_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Puja", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("Subastas.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("ImagenesVehiculo");

                    b.Navigation("Subastas");
                });
#pragma warning restore 612, 618
        }
    }
}
